spring:
  application:
    name: careerforge-backend

  profiles:
    default: dev

server:
  port: 8080

jwt:
  expiration: 86400000

info:
  app:
    name: CareerForge Backend
    description: Job and Internship Application Tracker
    version: 1.0.0